branch:
  only:
    - master

before_install:
# decrypt the dropbox credentials
  - openssl aes-256-cbc -K $encrypted_6d3a9c3fada0_key -iv $encrypted_6d3a9c3fada0_iv -in .dropbox_uploader.enc -out .dropbox_uploader -d
  - cp .dropbox_uploader $HOME/

install:
# install the dropbox upload script
  - cd $HOME
  - curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh" -o dropbox_uploader.sh
  - chmod +x dropbox_uploader.sh
# install the Agda binary
  - AGDATAR=$(./dropbox_uploader.sh list | tail -n 1 | sed 's/^.*\(Agda.*\)$/\1/')
  - ./dropbox_uploader.sh download $AGDATAR .
  - tar -xzvf $AGDATAR
  - cd $( basename $AGDATAR .tar.gz )
  - sudo ./deploy.sh
# install markdown, xelatex
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
  - sudo apt-get update
  - sudo apt-get install markdown
  - sudo apt-get install latexmk texlive texlive-xetex texlive-latex-extra texlive-math-extra texlive-fonts-extra
# install the XITS fonts
  - cd $HOME/build/gallais/proof-search-ILLWiL
  - mv fonts $HOME/.fonts

script:
# generate index page
  - markdown index.md > index.html
# generate pdfs
  - make
  - mkdir -p pdf
  - mv papers/latex/lps*.pdf pdf/
# generate html documentation
  - agda -i . -i equality -i stdlib/src/ --html lps/Examples.agda

after_success:
  - git init
  - git config user.name "Travis Worker"
  - git config user.email "travis@gallais.org"
  - git remote add upstream https://${GH_TOKEN}@github.com/gallais/proof-search-ILLWiL.git &>/dev/null
  - git fetch upstream && git reset upstream/gh-pages
  - git add -f html/* pdf/* index.html
  - git commit -m "Uploading snapshot $(date '+%m/%d/%y %H:%M')"
  - git push -q upstream HEAD:gh-pages &>/dev/null

notifications:
  email: false

env:
  global:
    secure: c7utkazOgeZevFJs2mk0v6r/Fc3/KpRfIUcttAeSstUaGRiR82Y3gQb71lgmPCCHuVjvC166JBWam7Mnk5ogHNtfDBvgl5n5hWZpNn/e9crWJQFUL795Ba7cQqI8DKCybbYyxeaAbTASf9z3A9B/Q3QoGCPJtjb7Sg1vK9rTmtI=
